### ISSUE TITLE
Why change the prediction to 0?

### ISSUE THREAD

**Issue by Insane235** [aHuiWang/CIKM2020-S3Rec#1]
Hi, may I ask in [line 267 of the trainer.py](https://github.com/aHuiWang/CIKM2020-S3Rec/blob/master/trainers.py#L267) , why do we need to change the prediction result of the input items to 0?

**Comment by Lancelot39** [comment]
Generally, the input items have been interacted by the user in the past, they are positive samples in some extent. So I think it is necessary to change its prediction result to 0.
Worth noting that some works have not considered it, because they think a robust recommendation system should be able to distinguish when to recommend proper items.

In my opinion, I think a fair comparison is in vital importance. If you agree anyone of the above view, all the experiments should be conducted in the same condition.

**Comment by aHuiWang** [comment]
> Generally, the input items have been interacted by the user in the past, they are positive samples in some extent. So I think it is necessary to change its prediction result to 0.
> Worth noting that some works have not considered it, because they think a robust recommendation system should be able to distinguish when to recommend proper items.
> 
> In my opinion, I think a fair comparison is in vital importance. If you agree anyone of the above view, all the experiments should be conducted in the same condition.

I agree with @Lancelot39. And I mainly refer to this [implementation](https://github.com/allenjack/HGN/blob/c3e4a2832b6b02b7fa28c4363112f3cb59b8aa02/run.py#L49).

**Comment by Insane235** [comment]
Thank you guys. I think it makes sense.
