### ISSUE TITLE
About dataset

### ISSUE THREAD

**Issue by flyz1** [aHuiWang/CIKM2020-S3Rec#4]
Hello author, I want to learn your code, but the data set I downloaded from the Internet seems to be missing some files. Can you share the download link of the data set?
For example, I can't find the file named "artist2attributes.json" or "artist2tags.json" in the LastFM data set, since I downloaded it from the Internet only have these files below :
![image](https://user-images.githubusercontent.com/43409572/117412249-24cebf00-af47-11eb-97d0-1bdaf53f5a5d.png)

Looking for your reply, thanks a million!

**Comment by aHuiWang** [comment]
Same problem as issues #3

**Comment by flyz1** [comment]
sorry, I didn't express it clearly. I mean there is no such file in the raw LastFM dataset that I download on the internet.
![image](https://user-images.githubusercontent.com/43409572/117433894-97976480-af5e-11eb-95be-fabe80df317c.png)

**Comment by aHuiWang** [comment]
Sorry, it's my fault. The 'json' file was generated from user_taggedartists.dat by aggregating different tags for artists. And the format can be referred to './data/LastFM_item2attributes.json'.

**Comment by flyz1** [comment]
OK! Thank you very much for your reply!

**Comment by Niyx52094** [comment]
Hi, I still have the question about how to get item2attributes.json, because after I aggregate the different tags for artists in "user_taggedartists.dat", the number of attributes is way much larger than 388 that the paper said, I wonder is there any process to filter the attributes and decrease the number of attributes to 388? you can see the number of attributes and the id are both different as below.
![image](https://user-images.githubusercontent.com/50197240/226178546-b0403c1b-71c5-4053-b2ee-94b723f06532.png)
